NewProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.index, name='index'),

    # /music/<album_id>/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    # /music/<album_id>/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

music/models.py
from __future__ import unicode_literals

from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song


def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums': all_albums})


def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {'album': album,
                                                     'error_message': "You did not select valid song"})
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

music/templates/music/base.html
{% load staticfiles %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title {% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
      <a class="navbar-brand" href="{% url 'music:index'%}">
        viberr
      </a>
    </div>

      <div class="collapse navbar-collapse" id="topNavBar">
          <ul class="nav navbar-nav">
             <li class="active"> <a href="{% url 'music:index'%}">
                 <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
             </a>
             </li>
               <li class=""> <a href="#">
                 <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
             </a>
             </li>
          </ul>

          <form class="navbar-form navbar-left" role="search" method="get" action="#">
              <div class="form-group">
                  <input type="text" class="form-control" name="q" value="">
              </div>
                    <button type="submit" class="btn btn-default">Search</button>
          </form>

         <ul class="nav navbar-nav navbar-right">
              <li class=""> <a href="#">
                 <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
             </a>
             </li>
              <li class=""> <a href="#">
                 <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
             </a>
             </li>
          </ul>
      </div>
  </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %} Details {% endblock %}

{% block body %}

<img src="{{ album.album_logo}}">
    <h1>{{album.album_title}}</h1>
    <h3>{{album.artist}}</h3>

    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>

    {% endif%}

    <form action="{% url 'music:favorite' album.id %}" method="post">
        {% csrf_token %}
        {% for song in album.song_set.all %}
        <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}" />
        <label for="song{{forloop.counter}}"> {{song.song_title}}
        {% if song.is_favorite %}
        <img src="https://www.google.com/imgres?imgurl=http%3A%2F%2Fimages.clipartpanda.com%2Fclipart-star-dT6okBaT9.jpeg&imgrefurl=http%3A%2F%2Fwww.clipartpanda.com%2Fcategories%2Fclipart-stars&docid=QSqsUp7k_JGODM&tbnid=1-F0qTBBkW0DZM%3A&w=1152&h=648&client=safari&bih=812&biw=1440&ved=0ahUKEwjXpp3XlJTOAhWJTSYKHQ5lCZoQMwhNKA4wDg&iact=mrc&uact=8"/>
    {% endif%}
        {% endfor %}
    </label>
        <br>
        <input type="submit" value="Favorite">

    </form>

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

    <h2>Here are all my albums</h2>
    {% if all_albums%}
        <ul>
            {% for album in all_albums %}
            <li> <a href="{% url 'music:detail' album.id %}"> {{album.album_title}} </a> </li>
            {%endfor%}
        </ul>
    {% else %}
        <h3>You have no albums :( </h3>
    {% endif %}

{% endblock %}